---
apiVersion: batch/v1
kind: Job
metadata:
  name: msalehjahromi-torchrun-ftn
  namespace: yn-gpu-workload
  labels:
    k8s-user: msalehjahromi
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    spec:
      nodeSelector:
        nvidia.com/cuda.runtime.major: "12"
        nvidia.com/gpu.machine: "DGXA100-920-23687-2530-000"
      securityContext:
        runAsUser: 271030
        runAsGroup: 600651
        fsGroup: 600651
        supplementalGroups:
          - 1944259512
          - 1944285520
          - 1944385884
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: '21474836480'  # 20 GB shared memory for efficient GPU communication
        - name: ifp
          persistentVolumeClaim:
            claimName: msalehjahromi-gpu-rsrch7-home-ip-rsrch
        - name: home
          persistentVolumeClaim:
            claimName: msalehjahromi-gpu-home
      containers:
        - name: main
          image: hpcharbor.mdanderson.edu/nnunetv2/nnunetv2@sha256:4ab016ba4b356842be74fbf58159480598bfc015c8454339022aa0fcbfdc196d
          command: ["torchrun"]
          args: [
            "--nproc_per_node=8", 
            "--nnodes=1", 
            "--node_rank=0", 
            "--master_addr=$(MASTER_ADDR)",
            "--master_port=$(MASTER_PORT)",
            "/rsrch1/ip/msalehjahromi/codes/FineTune/multiGPU/n_GPU_A100/2_run_fineTune_ddp_launcher.py"
          ]
          workingDir: "/rsrch1/ip/msalehjahromi"
          env:
            - name: HOME
              value: "/rsrch1/ip/msalehjahromi"
            - name: MASTER_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP  # Use the pod IP for MASTER_ADDR
            - name: MASTER_PORT
              value: "29500"  # Or any other unused port
            - name: NCCL_DEBUG
              value: "INFO"  # Enable NCCL debug logs
            - name: NCCL_SOCKET_IFNAME
              value: "eth0"  # Specify network interface
            - name: NCCL_IB_DISABLE
              value: "1"  # Disable Infiniband if not available
          volumeMounts:
            - name: shm
              mountPath: "/dev/shm"
            - name: ifp
              mountPath: "/rsrch7/home/ip_rsrch/wulab"
            - name: home
              mountPath: "/rsrch1/ip/msalehjahromi/"
          resources:
            limits:
              nvidia.com/gpu: "8"  # Request 4 GPUs for the test run
            requests:
              nvidia.com/gpu: "8"
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
